name: helmy
description: health project

version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2
  localstorage: ^4.0.0+1
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  buttons_tabbar: ^1.3.8
  table_calendar: ^3.0.8
  introduction_screen: ^3.1.14
  flutter_background_service: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/onBoarding1.png
    - assets/images/onBoarding2.png
    - assets/images/onBoarding3.png
    - assets/images/onBoarding4.png
  fonts:
    - family: Dohyeon
      fonts:
        - asset: assets/fonts/BMDOHYEON_ttf.ttf
          weight: 100


