name: helmy
description: health project

version: 1.0.0+3
environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^17.0.0
  shared_preferences: ^2.2.2
  localstorage: ^4.0.0+1
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  buttons_tabbar: ^1.3.8
  table_calendar: ^3.0.8
  introduction_screen: ^3.1.14
  flutter_background_service: ^5.0.5
  provider: ^6.1.2
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/helmyAppIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/helmyAppIcon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/helmyAppIcon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/helmyAppIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/onBoarding1.png
    - assets/images/onBoarding2.png
    - assets/images/onBoarding3.png
    - assets/images/onBoarding4.png
    - assets/logos/helmyLogo.png
  fonts:
    - family: Dohyeon
      fonts:
        - asset: assets/fonts/BMDOHYEON_ttf.ttf
          weight: 100


